server:
  #设置端口号
  port: 8080
  session-timeout: 1800

spring:
  jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
  #设置运行环境
  profiles:
    active: dev
  #上传文件大小限制
  servlet:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  devtools:
    restart:
      enabled: true
  freemarker:
      template-loader-path: classpath:/template/
      cache: false
      charset: UTF-8
      check-template-location: true
      content-type: text/html; charset=utf-8
      expose-request-attributes: true
      expose-session-attributes: true
      request-context-attribute: request

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Dao.xml
  type-aliases-package: cn.yiyang.model.domain