server:
  #设置端口号
  port: 8080
  session-timeout: 1800


#定义上传文件的路径
web:
  upload-path: D:/workspace/model/target/upload/

spring:
  jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
  #设置运行环境
  profiles:
    active: dev
  #上传文件大小限制
  servlet:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  devtools:
    restart:
      enabled: true
  freemarker:
      template-loader-path: classpath:/template/
      cache: false
      charset: UTF-8
      check-template-location: true
      content-type: text/html; charset=utf-8
      expose-request-attributes: true
      expose-session-attributes: true
      request-context-attribute: request
  #指定上传图片静态文件的位置，用于通过url精心访问
  mvc:
    static-path-pattern: /**
  resources:
#      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
      static-locations: file:${web.upload-path}

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Dao.xml
  type-aliases-package: cn.yiyang.model.domain